### ISSUE TITLE
Crash on Forge 1448

### ISSUE THREAD

**Issue by spannerman79** [MineMaarten/IGW-mod#30]
Forge 1448 - recommended according to Forge Download Page [here](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html)
Minecraft 1.7.10
IGW-mod 1.1.4-20
Related perhaps in a way to #26 

IGW-mod is client side only - not on server in this instance.

OpenEye crash report http://openeye.openmods.info/crashes/a7ec297d91d7ff47c087ca2d528e107d

Client side error - http://hastebin.com/efeburifik.avrasm

Server side displays;

    [FML]: NetworkDispatcher exception
    java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.7.0_80]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.7.0_80]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.7.0_80
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.7.0_80]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384) ~[?:1.7.0_80]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

**Comment by Deiwos** [comment]
Crashes occur both from clicking (any) links in the IGW UI, and from clicking on the Stone/Grass Block/Piston buttons at the bottom of the Blocks and Items list. Either way, the crash is caused by the same exception:
http://pastebin.com/46V29QA3

**Comment by MineMaarten** [comment]
If the OpenEye report is indeed the same crash, I've fixed it. Let me know after the version has been released (as soon as this issue closes)

**Comment by sandalle** [comment]
If by next release you mean [1.1.6-23](http://minecraft.curseforge.com/mc-mods/223815-in-game-wiki-mod/files/2247673), I still get [this client crash report](http://pastebin.com/RYyCK6aG) on SMP, but no crash on SSP, when clicking on a link such as "Intro" and "For Servers".

Client is running Forge 10.13.4.1448-1.7.10.
Server is running [KCauldron](http://tcpr.ca/kcauldron)-1.7.10-p1448.133.

**Comment by sandalle** [comment]
Tried with IGW Mod 1.1.11-32, client Forge 10.13.4.1566-1.7.10, server KCauldron 1.7.10-1566 and it works. Sorry for the delay in responding with results. :)
